on:
  push:
    branches: ["adding-actions"]

name: Create Release

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and save
        uses: docker/build-push-action@v3
        with:
          tags: dorsivan/roots-front:${{ env.RELEASE_VERSION }}
          outputs: type=docker,dest=/tmp/img.tar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.RELEASE_VERSION }}
          files: |
            /tmp/img.tar
