name: Create Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set vars 
        run: echo "KUBECONFIG=\"${GITHUB_WORKSPACE}/.k3s.yaml\"" >> $GITHUB_ENV

      # - name: override kubectl config file 
      #   run: cp  ${GITHUB_WORKSPACE}/.k3s.yaml ~/.kube/config

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dorsivan/roots-front:dev.3
#          tags: dorsivan/roots-front:dev.${{ github.sha }}
      
      # - name: try to set permissions
      #   run: chown 644 .k3s.yaml

      - name: helm upgrade 
        run: | 
          ls -la
          pwd
          helm upgrade mvp ci/k3s/roots-front/ --install --values=ci/k3s/roots-front/values.yaml --set image.tag=dev.3




